### ISSUE TITLE
求开放评论

### ISSUE THREAD

**Issue by zmofei** [Junior2Ran/junior2ran.github.io#1]
突然发现小哥哥的博客的评论关闭了
![image](https://user-images.githubusercontent.com/3351337/42766228-7000034a-894c-11e8-9de7-8f9adf4038eb.png)
求打开

**Comment by Junior2Ran** [comment]
@zmofei Accepted, working on it 👨‍🏭

**Comment by Junior2Ran** [comment]
由于Hypercomments取消了免费版，所以导致评论被关闭。
现已切换为gitment评论
